extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  browser: true
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 2021
settings:
  react:
    version: detect
rules:
  no-console: error
  prettier/prettier: [error, { endOfLine: auto }]
  react-hooks/exhaustive-deps: off
  react/prop-types: warn
overrides:
  - files:
      - '*.test.js'
    rules:
      react/display-name: off
      react/prop-types: off
  - files:
      - '*.config.js'
