extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - '@typescript-eslint'
env:
  browser: true
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2021
settings:
  react:
    version: detect
rules:
  no-console: error
  prettier/prettier: [error, { endOfLine: auto }]
  react-hooks/exhaustive-deps: off
  react/prop-types: warn
  '@typescript-eslint/explicit-module-boundary-types': off
overrides:
  - files:
      - '*.test.js'
    rules:
      react/display-name: off
      react/prop-types: off
  - files:
      - '*.config.js'
